name: Pull latest changes to main branch

on:
  pull_request:
    types: [merged]
    branches: [main]

jobs:
  pull-latest-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Pull latest changes
        run: git pull origin main
      - name: Commit and push changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git commit -am "Pull latest changes"
          git push
