name: Pull latest changes to main branch

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    if: "github.event.pull_request.merged == true"
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            ls -la
            cd "/bitnami/wordpress/deploy_bitnami_wordpress"
            ls -la
            git pull --ff-only
            git status
